### ISSUE TITLE
Project suspended

### ISSUE THREAD

**Issue by YuzukiTsuru** [YuzukiTsuru/lessampler#1]
Because I need to take the college entrance examination in China, the project development is suspended

**Comment by Toneyisnow** [comment]
Thanks for the info! I have read your project and it looks pretty interesting, and do you have instruction how to build it? Is this using CMAKE or GCC?

**Comment by YuzukiTsuru** [comment]
> Thanks for the info! I have read your project and it looks pretty interesting, and do you have instruction how to build it? Is this using CMAKE or GCC?

You need install JUCE library before build it.
with JUCE you can build it with many build tools

**Comment by YuzukiTsuru** [comment]
The project is restored, and a large amount of content needs to be reconstructed due to a long period of inactivity
