### ISSUE TITLE
Cannot build on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by fpesari** [YuzukiTsuru/lessampler#14]
Hello,

since you said we are welcome to participate to the test, I tried building lessampler on openSUSE Tumbleweed. These are the errors I get:

```
error: no matching function for call to 'find(std::vector<std::basic_ostream<char>*>::iterator, std::vector<std::basic_ostream<char>*>::iterator, std::ostream*)'
```

I get 4 of these. I attached the full log for context (just ctrl+f "error:" to find them). Thanks!
[lessampler_log.txt](https://github.com/YuzukiTsuru/lessampler/files/9306700/lessampler_log.txt)

**Comment by YuzukiTsuru** [comment]
This problem may be because of using gcc 12 version, I will confirm if this is the problem

**Comment by YuzukiTsuru** [comment]
![image](https://user-images.githubusercontent.com/12003087/184133325-c8b81b59-11fe-4eda-a93d-b756fe113dbf.png)
