### ISSUE TITLE
是否有Java或Js版本？

### ISSUE THREAD

**Issue by watersoft123** [YuzukiTsuru/lessampler#4]
你好，我想在手机上使用歌曲合成，请问这个有Java或JS版本的吗？谢谢！
我找到一个sinsy的js版本的，可是不支持中文，也找不到中文音源。sinsy的官网上倒是有中文，但却不开源。

**Comment by YuzukiTsuru** [comment]
使用安卓NDK可以编译为安卓软件包，不过项目还在进行中还无法使用
