### ISSUE TITLE
Generation of lessaudio files

### ISSUE THREAD

**Issue by VocAddict** [YuzukiTsuru/lessampler#6]
Currently lessampler 0.1.0 generates files for the entire folder if it has never been used before, even if it's one file from the folder (in the case of using multipitch/multiexpression banks). Can the behaviour be changed to only generate files for those needed in the render?

**Comment by YuzukiTsuru** [comment]
I have found this problem. In fact, the master has been modified to single output. I will release it soon.

**Comment by YuzukiTsuru** [comment]
Fix. https://github.com/YuzukiTsuru/lessampler/releases/tag/alpha.0.1.1
